export const GET_NEWS_TOPIC = 'GET_NEWS_TOPIC';
export const GET_NEWS_DATE = 'GET_NEWS_DATE';
export const GET_NEWS_SORTBY = 'GET_NEWS_SORTBY';
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';